update kernels3.cu for pascal architecture
This corrects the following error (see stackoverflow thread http://stackoverflow.com/questions/37566987/cuda-atomicadd-for-doubles-definition-error for details):

loading kernels ...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main_window.py", line 425, in run
    self)
  File "/home/tom/Desktop/test/GRAAL-master/main_gl.py", line 81, in __init__
    self.fasta_file, candidates_blacklist, self.allow_repeats)
  File "/home/tom/Desktop/test/GRAAL-master/simulation_loader.py",
line 107, in __init__
    fact_sub_sampling)
  File "/home/tom/Desktop/test/GRAAL-master/cuda_lib_gl.py", line 374,
in __init__
    self.loadProgram('kernels3.cu')
  File "/home/tom/Desktop/test/GRAAL-master/cuda_lib_gl.py", line 713,
in loadProgram
    self.module = pycuda.compiler.SourceModule(fstr, no_extern_c=True,
options=["-keep", "-m64", "-cubin"])
  File "/usr/local/lib/python2.7/dist-packages/pycuda-2016.1.2-py2.7-linux-x86_64.egg/pycuda/compiler.py",
line 265, in __init__
    arch, code, cache_dir, include_dirs)
  File "/usr/local/lib/python2.7/dist-packages/pycuda-2016.1.2-py2.7-linux-x86_64.egg/pycuda/compiler.py",
line 255, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "/usr/local/lib/python2.7/dist-packages/pycuda-2016.1.2-py2.7-linux-x86_64.egg/pycuda/compiler.py",
line 137, in compile_plain
    stderr=stderr.decode("utf-8", "replace"))
CompileError: nvcc compilation of /tmp/tmpLug94l/kernel.cu failed
[command: nvcc --cubin -keep -m64 -cubin -arch sm_61
-I/usr/local/lib/python2.7/dist-packages/pycuda-2016.1.2-py2.7-linux-x86_64.egg/pycuda/cuda
kernel.cu]
[stderr:
kernel.cu(37): error: function "atomicAdd(double *, double)" has
already been defined