fixed wx wildcard string bug in main_window.py
This fix corrects the following error:

Traceback (most recent call last):
  File "main_window.py", line 325, in OnLoadFasta
    dd = wx.FileDialog(None, "Select Fasta File","", "", wcd,
wx.FD_OPEN | wx.FD_FILE_MUST_EXIST)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_windows.py",
line 3139, in __init__
    _windows_.FileDialog_swiginit(self,_windows_.new_FileDialog(*args,
**kwargs))
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at
../src/common/filefn.cpp(1685) in wxParseCommonDialogsFilter():
missing '|' in the wildcard string!